# $Id: run.mac 100673 2016-10-31 10:43:05Z gcosmo $
#
# Macro file for "AnaEx01.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run.mac
#

/control/verbose 1
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
#
# initialize
/run/initialize
#

/gps/particle gamma
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 -400 95.5 mm
/gps/pos/radius 1.5 mm
/gps/pos/inner_radius 0
/gps/direction 0 1 0
/gps/energy 662 keV
/run/beamOn 100000

